openapi: 3.0.0
info:
  title: RescueMe API
  description: API de ejemplo mínima para probar Swagger UI
  version: "1.0.0"
paths:
  /hello:
    get:
      summary: Devuelve un saludo
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Hola desde Swagger"
